version: "3"

services:
  default:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: es01
    volumes:
      - ./data:/usr/share/elasticsearch/data
    networks:
      - elastic
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    container_name: kb01
    environment:
      ELASTICSEARCH_HOSTS: "http://es01:9200"
    ports:
      - "5601:5601/tcp"
    networks:
      - elastic
    depends_on:
      - es01

  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.2
    container_name: ls01
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
    ports:
      - "5140:5140"
    networks:
      - elastic
    environment:
      xpack.monitoring.enabled: false
    depends_on:
      - es01

networks:
  elastic:
